# Generated by Django 5.2.9 on 2025-12-03 09:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, help_text='Icon name or emoji', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Facilities',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('pin_code', models.CharField(max_length=10)),
                ('board', models.CharField(choices=[('IGCSE', 'IGCSE'), ('CBSE', 'CBSE'), ('IB', 'International Baccalaureate'), ('ICSE', 'ICSE'), ('State', 'State Board')], max_length=50)),
                ('grades_offered', models.CharField(help_text="Comma-separated grades (e.g., '1,2,3,4,5,6,7,8,9,10,11,12')", max_length=100)),
                ('co_ed_type', models.CharField(choices=[('B', 'Boys'), ('G', 'Girls'), ('C', 'Co-ed')], default='C', max_length=1)),
                ('distance', models.DecimalField(decimal_places=2, help_text='Distance in km', max_digits=5)),
                ('bus_availability', models.BooleanField(default=False)),
                ('syllabus', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True)),
                ('curriculum_website', models.URLField(blank=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='schools/')),
                ('fees_by_grade', models.TextField(blank=True, help_text="Format: '12:400000,11:380000' for grade 12: ₹400000, grade 11: ₹380000")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facilities', models.ManyToManyField(blank=True, to='schools.facility')),
            ],
            options={
                'ordering': ['-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('reviewer_name', models.CharField(max_length=100)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='schools.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
