# Generated by Django 5.2.9 on 2025-12-06 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='board',
            field=models.CharField(choices=[('IGCSE', 'IGCSE'), ('CBSE', 'CBSE'), ('IB', 'International Baccalaureate'), ('ICSE', 'ICSE'), ('State', 'State Board')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='school',
            name='bus_availability',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='school',
            name='distance',
            field=models.DecimalField(db_index=True, decimal_places=2, help_text='Distance in km', max_digits=5),
        ),
        migrations.AlterField(
            model_name='school',
            name='grades_offered',
            field=models.CharField(db_index=True, help_text="Comma-separated grades (e.g., '1,2,3,4,5,6,7,8,9,10,11,12')", max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='location',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='school',
            name='pin_code',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='school',
            name='rating',
            field=models.DecimalField(db_index=True, decimal_places=1, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
