# Generated by Django 5.2.9 on 2025-12-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_alter_school_board_alter_school_bus_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='google_maps_link',
            field=models.URLField(blank=True, help_text='Google Maps URL for the school location'),
        ),
    ]
