# Generated by Django 5.2.9 on 2025-12-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_school_google_maps_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='address_line_1',
            field=models.CharField(blank=True, help_text='First line of address', max_length=200),
        ),
        migrations.AddField(
            model_name='school',
            name='address_line_2',
            field=models.CharField(blank=True, help_text='Second line of address', max_length=200),
        ),
        migrations.AddField(
            model_name='school',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number of the school', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='review_count',
            field=models.IntegerField(db_index=True, default=0, help_text='Number of reviews'),
        ),
    ]
