# Generated by Django 5.2.9 on 2025-12-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_school_address_line_1_school_address_line_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='top_review',
            field=models.TextField(blank=True, help_text='Top review from Google Maps'),
        ),
    ]
