# Generated by Django 5.2.9 on 2025-12-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_school_top_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='curriculum_website',
            field=models.CharField(blank=True, help_text='Curriculum website URL', max_length=500),
        ),
        migrations.AlterField(
            model_name='school',
            name='google_maps_link',
            field=models.CharField(blank=True, help_text='Google Maps URL for the school location', max_length=500),
        ),
        migrations.AlterField(
            model_name='school',
            name='website',
            field=models.CharField(blank=True, help_text='School website URL', max_length=500),
        ),
    ]
