# Generated by Django 5.2.9 on 2025-12-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(blank=True, help_text='e.g., IB, IGCSE', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('subjects', models.TextField(help_text='Comma-separated list of subjects')),
                ('exams', models.TextField(blank=True, help_text='Information about exams')),
                ('info', models.TextField(blank=True, help_text='Additional information')),
                ('website', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Curricula',
            },
        ),
    ]
