# Generated by Django 6.0 on 2025-12-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='wikipedia_page',
            field=models.CharField(blank=True, help_text='Wikipedia page title (optional, auto-detected if blank)', max_length=200),
        ),
    ]
